/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'price' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'user' : Principal,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export interface OrderItem { 'quantity' : bigint, 'menuItemId' : bigint }
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'inPreparation' : null } |
  { 'delivered' : null };
export type Time = bigint;
export interface _SERVICE {
  'createMenuItem' : ActorMethod<[string, string, bigint, string], MenuItem>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getOrderStatus' : ActorMethod<[bigint], OrderStatus>,
  'placeOrder' : ActorMethod<[Array<OrderItem>], Order>,
  'setMenuItemAvailability' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];