/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'inPreparation' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [MenuItem],
      [],
    ),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Nat], [OrderStatus], ['query']),
  'placeOrder' : IDL.Func([IDL.Vec(OrderItem)], [Order], []),
  'setMenuItemAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'inPreparation' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'quantity' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    'createMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [MenuItem],
        [],
      ),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Nat], [OrderStatus], ['query']),
    'placeOrder' : IDL.Func([IDL.Vec(OrderItem)], [Order], []),
    'setMenuItemAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };